sonar.organization=messaging-go
sonar.projectKey=messaging-go_integration-template

# relative paths to source directories. More details and properties are described
# in https://sonarcloud.io/documentation/project-administration/narrowing-the-focus/
sonar.sources=.
sonar.go.tests.reportPaths = ./test-report.json
sonar.go.coverage.reportPaths=./cover.out

sonar.exclusions=**/vendor/**,**/*_test.go,release.config.js
sonar.cpd.exclusions=**/*_test.go,test/**/*
sonar.test.exclusions=**/*_test.go,test/**/*
